### ISSUE TITLE
sketch compilation problem + loader appears to be borked

### ISSUE THREAD

**Issue by Dolnor** [stooged/PS4-Server-900u#10]
Hi,

Firstly, the recent introduction of the ability to connect to a Wi-Fi network has broken the build sketch compiling due to data type miscast.

> no matching function for call to 'ESP8266WiFiClass::begin(String&, String&)'
which can be remedied by casting to c-string char array
`WiFi.begin(WIFI_SSID.c_str(), WIFI_PASS.c_str());`

What's beyond me however is the recent changs to the way SPIFFS are managed and loading the bins directly opposed to having them converted to a html page. Whenever I select a payload from index/payloads.html nothing appears to happen, no text is display, only the navy blue background perists and that's that. I've tried uploading a custom index.hml from #8, but alas it's the same thing - nothing happens what so ever as if the function is not being triggered.

**Comment by stooged** [comment]
with the esp8266 lib are you using version 3.0.1 or above?

the begin function has string data types on line 42. 
https://github.com/esp8266/Arduino/blob/master/libraries/ESP8266WiFi/src/ESP8266WiFiSTA.h#L42

```

begin(const String& ssid, const String& passphrase = emptyString, int32_t channel = 0, const uint8_t* bssid = NULL, bool connect = true);

```

with the changes to the loader and html the esp8266 should handle all of the html and all you should need are the .bin files in the spiffs.

when you select a payload it should navigate to loader.html and you should see "Loading Exploit, Please Wait ..." 

i would check if `loader.html` is able to be reached and check its source to make sure it is being compiled and served properly.

if you are not using the latest esp8266 library maybe try and update it and see if that changes something because the loader.html is stored in <a href=https://www.arduino.cc/reference/en/language/variables/utilities/progmem/>progmem</a> and it is served using a data type that can handle a const char stored in progmem.
i am not sure if the older esp8266 libs have that functionality, my version is 3.0.1 and the latest is 3.0.2.

https://github.com/esp8266/Arduino

if all of that fails you can still upload your own html like the older versions before the changes i made, you can upload your own index.html and html payloads.
the server only loads the internal pages if they are absent so on the spiffs.

you could grab the html files from this commit and upload them to the spiffs and it should work like it did before i moved the loader to progmem.

https://github.com/stooged/PS4-Server-900u/tree/52737108d82ecc8a5db5fccf16c8b326d3b2422b/PS4_Server_900u/data

i only have d1 mini and d1 mini pro boards to test with so i dont know if other boards could be a cause for the issue, i suspect it might be library versions causing it.

**Comment by Dolnor** [comment]
I was on community version 2.4.2., needless to say, updating to 3.0.2. did resolve both of my problems from this issue. Appreciate the deatailed response and thank you for the great work on this! Apologies for issues that aren't actually issues.

I bet I won't be the last person to crawl from under a rock, so a suggestion, if I may - perhaps library dependencies need to be listed somewhere in the main readme.
