### ISSUE TITLE
update to lastest exploite

### ISSUE THREAD

**Issue by peyman4774** [stooged/PS4-Server-900u#12]
https://github.com/ChendoChap/pOOBs4

**Comment by Doyle4** [comment]
Instead of me making a new issue, I do apologise to jump onto this one.

Is it possible for my self to add the new xploit files or will I need to wait for a new compiled firmware?
If possible to do my self, if ok and you have time, would it be ok for a description on how to do so? Thank you.

The new exfathax_pico.img works fine with old webkit which is nice. 6kb from 4.1mb...crazy.

**Comment by stooged** [comment]
I will have a look.
The patch notes state that it may be worse so some testing will be required.

**Comment by Doyle4** [comment]
Thanks for the update.

Im going to hold back until you are happy with it.

Thanks again.

**Comment by stooged** [comment]
i added the changes made by chendochap.
try it out and see how you go.

the changes are all in loader.h so you can just update that one file.

**Comment by Doyle4** [comment]
Amazing thank you!

Will report back if any issues.
Thanks again.
