### ISSUE TITLE
bin-inject

### ISSUE THREAD

**Issue by peyman4774** [stooged/PS4-Server-900u#2]
Hi, What is Benefits of bin-inject vs html.gz ?

**Comment by stooged** [comment]
with bin2html/gz you take the .bin file and use the python script to convert the .bin file into a static html file that loads the bin into the console memory.
each time you update a bin file you have to convert it into the html/gz.


bin-inject does the same thing using javascript but you do not need to convert bin files etc, the single loader.html will read any .bin file you set and it will load that .bin file into the console memory.
each time you update a bin file you just update the .bin without needing to convert or modify code.


the end result is the same for both variants, the payload gets loaded into the console without needing to use netcat or binloader.

i use bin inject for mine and my friends consoles and it makes it easy for them to update their own .bin files because they just upload the .bin to their esp8266/32 boards and they do not need to learn how to run python and convert files.
