### ISSUE TITLE
Request: removing alert

### ISSUE THREAD

**Issue by Leerz** [stooged/PS4-Server-900u#5]
finally got everything working 
didn't have 1.1k resistor so i used 1k and 5k for high

everything works as it should. although I'm trying to fool around with the code and attempting to remove the alertbox and adding a settimeout instead, but it seems to not work, i tried 10seconds to 30 seconds and a combination of both to add as much delay
i've tested numerous times on normal alert and it shows within 8 seconds and hitting ok loads the payload just fine.

`//ESP8266 enable usb - stooged

  enableUSB();

  //alert("Click OK When You See The Popup Notification");

  showMessage("waiting for prompt");

  setTimeout(showMessage("waiting for prompt"), 30000); `

maybe it's interfering with chain.run and causing issues.

all i want is a one click loader LOL 

p.s i read your note about killing webkit and i added window.close() at the end but i'm sure you have a more elegant process

**Comment by stooged** [comment]
the alert() function basically stops code execution at the point of the alert() until you close it.
the settimeout() function allows the code to continue executing and at a set interval will execute the defined function.
https://developer.mozilla.org/en-US/docs/Web/API/setTimeout

by using settimeout the code will just continue and look for the usbhax and it will fail because there is no pause in code execution to give time for the usb device to load.

you need to stop the code execution and allow time for the usb to load and then continue.

you can try using async functions and then use await to pause the code execution, await will not work unless it is inside an "async function()"

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function

you could try modifying the trigger_spray function to be an async function like this
`var trigger_spray = async function () {`

and then where the alert popup is put an await to pause the code at that point like this
`await new Promise(r => setTimeout(r, 5000));`

**Comment by stooged** [comment]
the alert() function basically stops code execution at the point of the alert() until you close it.
the settimeout() function allows the code to continue executing and at a set interval will execute the defined function.
https://developer.mozilla.org/en-US/docs/Web/API/setTimeout

by using settimeout the code will just continue and look for the usbhax and it will fail because there is no pause in code execution to give time for the usb device to load.

you need to stop the code execution and allow time for the usb to load and then continue.

you can try using async functions and then use await to pause the code execution, await will not work unless it is inside an "async function()"

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function

try modifying the trigger_spray function to be an async function like this
`
var trigger_spray = async function () {
`

and then where the alert popup is put an await to pause the code at that point like this
`
await new Promise(r => setTimeout(r, 5000));
`


if you are unsure what i mean try this
it does work without the alert popup but the time to wait might need to be adjusted to suit your ps4/usb stick.
i used 5000ms in my tests and it works but you still might get the ps4 browser error during the exploit which requires a click. 


```C
var trigger_spray = async function () {
    //Make socket <= 0xFF | -> alloc 0x800
 
 
    var NUM_KQUEUES = 0x1B0;
    var kqueue_ptr = p.malloc(NUM_KQUEUES * 0x4);
    //Make Kqueues
    {
        for (var i = 0; i < NUM_KQUEUES; i++) {
            chain.fcall(window.syscalls[362]);
            chain.write_result4(kqueue_ptr.add32(0x4 * i));
        }
    }
    chain.run();
    var kqueues = p.array_from_address(kqueue_ptr, NUM_KQUEUES);
 
    var that_one_socket = chain.syscall(97, 2, 1, 0);
    if (that_one_socket.low < 0x100 || that_one_socket.low >= 0x200) {
        alert("invalid socket");
        while (1);
    }
 
    //Spray kevents
    var kevent = p.malloc(0x20);
    p.write8(kevent.add32(0x0), that_one_socket);
    p.write4(kevent.add32(0x8), 0xFFFF + 0x010000);
    p.write4(kevent.add32(0xC), 0x0);
    p.write8(kevent.add32(0x10), 0x0);
    p.write8(kevent.add32(0x18), 0x0); {
        for (var i = 0; i < NUM_KQUEUES; i++) {
            chain.fcall(window.syscalls[363], kqueues[i], kevent, 0x1, 0x0, 0x0, 0x0);
        }
    }
    chain.run();
 
    //Fragment memory
    {
        for (var i = 20; i < NUM_KQUEUES; i += 2) {
            chain.fcall(window.syscalls[6], kqueues[i]);
        }
    }
    chain.run();
 
    //Trigger OOB
 
  //ESP8266 enable usb - stooged
  enableUSB();
  //alert("Click OK When You See The Popup Notification");
  await new Promise(r => setTimeout(r, 5000));
 
    //Trigger corrupt knote
    {
        for (var i = 1; i < NUM_KQUEUES; i += 2) {
            chain.fcall(window.syscalls[6], kqueues[i]);
        }
    }
    chain.run();
  if (chain.syscall(23, 0).low == 0) {
    disableUSB();
    return;
  }
  disableUSB();
  alert("failed to trigger exploit kernel heap might be corrupted, try again or reboot the console");
    p.write8(0, 0);
  return;
}
```

**Comment by stooged** [comment]
the alert() function basically stops code execution at the point of the alert() until you close it.
the settimeout() function allows the code to continue executing and at a set interval will execute the defined function.
https://developer.mozilla.org/en-US/docs/Web/API/setTimeout

by using settimeout the code will just continue and look for the usbhax and it will fail because there is no pause in code execution to give time for the usb device to load.

you need to stop the code execution and allow time for the usb to load and then continue.


EDIT: scratch what i posted, it was not a very good method but i have come up with something that should work and i will update the repo after a few more tests if it all goes well and it will remove the need for you to click the alert.

**Comment by stooged** [comment]
10000ms seems to be the sweet spot on my ps4

**Comment by stooged** [comment]
updated repo to automate usb wait(remove alert), see how you go with it.

**Comment by Leerz** [comment]
i must say that is indeed elegant. it works wonderfully! awesome work!!

now i will screw around with using just 1 payload and or autoloading that payload if no xxx is selected and then killing webkit afterwards :D

**Comment by stooged** [comment]
put this into a file and name it index.html then upload it to the esp8266 spiffs and it should load goldhen and not the payload list.


```
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>ESP Server</title>
<script>
function setpayload(payload,title)
{
   sessionStorage.setItem('payload', payload);
   sessionStorage.setItem('title', title);
   window.open("loader.html", "_self");
}
</script>
<style>
.btn {
    background-color: DodgerBlue;
    border: none;
    color: white;
    padding: 12px 16px;
    font-size: 16px;
    cursor: pointer;
	font-weight: bold;
}
.btn:hover {
    background-color: RoyalBlue;
}

body {
	background-color: #1451AE;
	color: #ffffff;
	font-size: 14px;
	font-weight: bold;
	margin: 0 0 0 0.0;
	overflow-y:hidden;
	text-shadow: 3px 2px DodgerBlue;
} 

.main {
	padding: 0px 0px;
	position: absolute; 
	top: 0; 
	right: 0;
	bottom: 0; 
	left: 0;
	overflow-y:hidden;
}
</style>
</head>
<body onload="setpayload('GoldHEN+v2.0b2.bin','GoldHEN v2.0b2');">
</body>
</html>
```
